webapp:
  service:
    annotations:
      {
        cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "neg-airbyte-webapp"}}}',
        controller.autoneg.dev/neg: '{"backend_services":{"80":[{"name":"airbyte-lb-backend-default","max_rate_per_endpoint":100}]}}',
      }
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 512Mi
podSweeper:
  resources:
    limits:
      cpu: 0.5
      memory: 256Mi
    requests:
      cpu: 0.25
      memory: 128Mi
server:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi
worker:
  resources:
    limits:
      cpu: 0.5
      memory: 3Gi
    requests:
      cpu: 0.25
      memory: 2Gi
postgresql:
  enabled: false
externalDatabase:
  database: airbyte
minio:
  enabled: false
global:
  state:
    storage:
      type: GCS
  logs:
    s3:
      enabled: false
      bucket: ""
      bucketRegion: ""
    minio:
      enabled: false
    storage:
      type: GCS
  jobs:
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 0.25
        memory: 2Gi
serviceAccount:
  annotations:
    {
      iam.gke.io/gcp-service-account: ${airbyte_sa}
    }
